sudo: false
language: c
matrix:
  include:
    - os: linux
      compiler: gcc
    - os: linux
      compiler: clang
#    - os: osx
#      compiler: gcc
#    - os: osx
#      compiler: clang
addons:
  apt:
    sources:
    # contains CMake 2.8.12
    - kubuntu-backports
    packages:
    - cmake
    - rpm
cache:
  directories:
  - download-cache
  - $HOME/.cache/pip
script:
  - pip install --user autobahntestsuite
  - wstest --autobahnversion
  - ./.travis.install.sh download-cache
#  - autoreconf -ifv
#  - ./configure --enable-autobahntest=yes LVRTE_DIR=$TRAVIS_BUILD_DIR/download-cache/ LVRTE_LIB=liblvrtdark.so
#  - make
#  - readelf -Ws .libs/libftw.so | awk '$4 == "FUNC" && $5 == "GLOBAL" && $7 != "UND"'
#  - make check
#  - ./build-ftw.sh
  - cmake --version
  - cmake -DCMAKE_C_COMPILER=$CC
  - cmake -Wdev
  - mkdir build
  - cd build
  - cmake -DWS_AUTOBAHN_TESTS=ON ..
  - cmake --build .
  - ctest --output-on-failure -C Debug
