sudo: false
language: c
os:
  - linux
#  - osx
compiler:
  - gcc
  - clang
addons:
  apt:
    packages:
    - rpm
#    - alien
cache:
  directories:
  - download-cache
  - $HOME/.cache/pip
install:
  - pip install --user autobahntestsuite
  - wstest --autobahnversion
script:
  - ./.travis.install.sh download-cache
  - ./build-ftw.sh liblvrtdark.so $TRAVIS_BUILD_DIR/download-cache/
matrix:
  allow_failures:
    - os: osx
