#sudo: required
sudo: false

os:
  - linux
#  - osx

language: c

compiler:
- gcc
#  - clang

addons:
  apt:
    packages:
#    - alien

cache:
  directories:
  - download-cache

script:
  - ./.travis.install.sh download-cache
  - ./build-ftw.sh liblvrtdark.so $TRAVIS_BUILD_DIR/download-cache/

matrix:
  allow_failures:
    - os: osx
