os:
  - linux
  - osx

branches:
  only:
    - master

language: c

compiler:
  - gcc
  - clang

install:
  - sudo apt-get update
  - sudo apt-get install autoconf
  - autoconf --version

script: "./build-ftw.sh"
