sudo: required

os:
  - linux
  - osx

branches:
  only:
    - master

language: c

compiler:
  - gcc
  - clang

install:
  - autoconf --version
  - ./.travis.install.sh

script: "./build-ftw.sh"

matrix:
  allow_failures:
    - os: osx
